### ISSUE TITLE
Add auto-fix

### ISSUE THREAD

**Issue by ai** [browserslist/lint#2]
We need to add auto-fix for errors:

* `missedNotDead`: add `not dead` to the end.
* `countryWasIgnored`: add `>0.3%` to the end (or replace other `>` query)?
* `limitedBrowsers`: add `last 2 versions, not dead`.
* `alreadyDead`: remove dead browser

We need to change tool API: `lint() => { id, message }[]` → `lint() => { id, message, fixed }[]`

**Comment by avivasyuta** [comment]
Hi. What do you mean by `fixed`? Is it fixed part of query? 
It would be great to see a couple of examples.

**Comment by ai** [comment]
* `last 2 version` → `last 2 versions, not dead`
* `last 2 version` → `last 2 version, >0.3%`
* `last 1 chrome version` → `last 1 chrome version, last 2 versions, not dead`
* `defaults, >1%, not IE 11` → `defaults, >1%`

**Comment by Fyzu** [comment]
> We need to change tool API: lint() => { id, message }[] → lint() => { id, message, fixed }[]

Where in this signature is the corrected result? always put the fixed version in `fixed`?

**Comment by ai** [comment]
> always put the fixed version in fixed?

yes

**Comment by rawr51919** [comment]
Wasn't this already fixed in #3?
